baseURL = "https://qin.kqh.me/"
languageCode = "zh"
title = "赫赫琴藏"
enableRobotsTXT = true
theme = "CJK"
disablePathToLower = true
hasCJKLanguage = true
uglyURLs = false
rssLimit = 20

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4
    
[taxonomies]
author = "author"
tag = "tag"
category = "category"
toc = "toc"

[author] # essential
name = "赫赫琴藏"

[sitemap] # essential
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[[menu.nav]]
name = "主頁"
weight = 1
url = "/"

[params]
Sections1 = [
  "post",
  "qinpu"
]
contentCopyright = ''
vertical = true
summaries = false # Set to true to show summaries of posts on homepage
divider = false #\a0 Set to false to remove divider below posts on homepage
schema = false # Set to true to add Schema.org metadata
opengraph = false # Set to true to add Open Graph metadata
twittercards = false # Set to true to add Twitter Cards metadata
repository = "https://github.com/kujihhoe/ChunqiuXuekan/blob/master/content/"
